# Generated by Django 2.1.7 on 2019-03-11 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth', models.CharField(choices=[('user', 'user'), ('group', 'group'), ('public', 'public'), ('all', 'all')], default='user', max_length=8, verbose_name='アクセス権')),
                ('title', models.CharField(max_length=256, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('is_directory', models.BooleanField(default=False, verbose_name='ディレクトリ')),
                ('headline', models.CharField(blank=True, default='', max_length=64, verbose_name='見出し')),
                ('permit_comment', models.BooleanField(default=False, verbose_name='コメント許可')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_directory'],
            },
        ),
    ]
